[tool.poetry]
name = "pyRobotiqGripper"
version = "1.0.0"
description = "Library to control Robotiq grippers from python"
authors = ["Benoit CASTETS <opensourceing@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"